name: Java CI (manual compile)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Compile all Java files in src
        run: |
          mkdir -p out
          # Jika semua .java ada langsung di src/, ini cukup:
          javac -d out src/*.java
          # Jika ada kemungkinan subfolder, gunakan:
          # javac -d out $(find src -name "*.java")

      - name: Run Codelab1 (jika punya main)
        run: java -cp out Codelab1

      - name: Run Codelab2 (jika punya main)
        run: java -cp out Codelab2
