name: Java CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 👇 path disesuaikan dengan folder kamu
      - name: Compile Java
        run: |
          mkdir -p out
          javac -d out $(find "Modul 1/Codelab/src" -name "*.java")

      - name: Run Program (contoh Codelab1)
        run: java -cp out Codelab1
